### ISSUE TITLE
Add documentation on most important projects

### ISSUE THREAD

**Issue by cbrxyz** [amazingmarvin/MarvinAPI#12]
I don't see attributes on projects that marks/unmarks them as MIPs. How do you set these via the database or API?

**Comment by amazingmarvin** [comment]
See https://github.com/amazingmarvin/MarvinAPI/wiki/Marvin-Data-Types#mips

**Comment by cbrxyz** [comment]
Am I doing something wrong?

When I send a GET request to that URL, I get a HTTP 500 error with the text `'Failed to retrieve labels\n'`. Tried at two different points today, a few hours apart, and got the same response.

I tried `/api/kudos` with the same API/full access keys and everything seems to be working fine on that endpoint.

**Comment by amazingmarvin** [comment]
The error message is wrong and should be "Failed to retrieve document". Probably the reason the request fails is that I put the wrong URL. Should be `?id=MIP`. Will fix.

**Comment by cbrxyz** [comment]
Got it now! Thanks 👍
