### ISSUE TITLE
How to change scheduling of a task through the DB?

### ISSUE THREAD

**Issue by cbrxyz** [amazingmarvin/MarvinAPI#17]
What keys need to be changed on a task document to change when it is scheduled in the day? I'm trying to produce an effect similar to dragging a task into my agenda in the UI through the API.

It looks like `title` gets prepended with a timestamp, but is that it? Thanks.

**Comment by amazingmarvin** [comment]
You can put the time anywhere in the title, but if if you put it at the start ("9:00 example") or at the end with "at" ("example at 9:00"), then the time is suppressed when shown in the calendar/agenda.

I also add the `taskTime` field even if reminders are off, which is the time formatted as `HH:mm`. But I'm not sure if this is used anywhere other than reminders.

**Comment by cbrxyz** [comment]
To change the time the task is scheduled for then you'd have to remove the time set on the task and then add a new time to the task right? Like:

`title = '9:15 Walk the dog'`
`title = 'Walk the dog'`
`title = '10:15 Walk the dog'`

Or you could just skip the second step. But do you have a RegEx that can find Marvin time formats and remove them? If not I can make one myself, but if you already have one, that'd be helpful.

**Comment by amazingmarvin** [comment]
You can skip the second step.

This is part of a much larger regex, so you might have to tweak it. But Marvin is using:

```javascript
/(?:0?\d|1[0-2])(?::[0-5][0-9])? ?(?:am|pm)\b|(?:0?\d|1\d|2[0-4]):[0-5][0-9]\b/i
```

**Comment by cbrxyz** [comment]
Awesome, thanks! That RegEx works great!
