### ISSUE TITLE
Using webhooks with a localhost server

### ISSUE THREAD

**Issue by jbriales** [amazingmarvin/MarvinAPI#25]
As a noob with web technologies, I'm not sure if this is even possible but let me raise/ask:
Is it possible to setup webhooks to send requests to a URL in the local machine, like http://localhost:5000/ ?
I'm trying that but it does not seem to work, so I'm not sure if it is not expected to work or I'm doing sth else wrong.

**Comment by cori** [comment]
I can’t speak to the Marvin-specific elements here, but generally if your local device is running something on that port and _is accessible to the internet_ there it would work, but your local device needs to be always-on and always-connected for it to be reliable. In my home network, for example, my local devices are not accessible to the internet directly, and that’s typically a pretty good policy.

You could try something like [ngrok](https://ngrok.com/) to expose your local app, but that adds a fair amount of complexity.

**Comment by amazingmarvin** [comment]
Yes! I use a local webserver to test webhooks so this works for sure. Just make sure you have CORS setup. It might look something like this:

```go
func LogMe(w http.ResponseWriter, r *http.Request) {
	if r.Method == "OPTIONS" {
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.Header().Set("Access-Control-Allow-Methods", "*")
		w.Header().Set("Access-Control-Allow-Headers", "*")
		return
	} else {
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.Header().Set("Access-Control-Allow-Methods", "*")
		w.Header().Set("Access-Control-Allow-Headers", "*")
	}

        fmt.Printf("%s %s", r.Method, r.URL.Path)

	body, err := ioutil.ReadAll(r.Body)
	if err != nil {
		http.Error(w, "Internal server error", http.StatusInternalServerError)
		return
	}

        fmt.Printf("%s", string(body))
}
```

**Comment by jbriales** [comment]
Uhmm I was doing sth similar. Does it need to be an https protocol vs http, or are both acceptable?

**Comment by amazingmarvin** [comment]
@jbriales Either should work. My test server uses http.

**Comment by RogueArt** [comment]
@jbriales Hi, I noticed in my testing / development that it was only HTTPS that worked, not HTTP. I made issue #53 since I got confused here as well, since my CORS and everything else matched the above, except for it being HTTP
