### ISSUE TITLE
[BUG] Suddenly getting 'Failed to retrieve document'

### ISSUE THREAD

**Issue by jbriales** [amazingmarvin/MarvinAPI#26]
**Statement of purpose**

I do solemnly swear (or affirm) that this is an API bug, and not a Marvin bug. For Marvin bugs I would use the in-app "?→Contact Support" feature

**Describe the bug**
Getting
> Failed to retrieve document

with error code 500
when using some endpoints.

**Endpoint(s) in question**
`/api/trackedItem`
Others seem to work.

**To Reproduce**
`curl -H "..." https://serv.amazingmarvin.com/api/trackedItem` with the right `X-API-Token`.

**HTTP client:**
Any (curl, fetch, http in node.js).

**Additional context**
The actions above used to work as of yesterday. Suddenly stopped working today.

Other API endpoints seem to work. E.g. these work:
```
curl https://serv.amazingmarvin.com/api/
curl -H "X-API-Token: $MARVIN_TOKEN" https://serv.amazingmarvin.com/api/todayItems
curl -H "X-API-Token: $MARVIN_TOKEN" https://serv.amazingmarvin.com/api/categories
curl -H "X-API-Token: $MARVIN_TOKEN" -XPOST -d '{"title": "Foo API via HTTP task"}' https://serv.amazingmarvin.com/api/addTask
curl -H "X-API-Token: $MARVIN_TOKEN" https://serv.amazingmarvin.com/api/me
```

**Comment by jbriales** [comment]
`curl -H "X-API-Token: $MARVIN_TOKEN" https://serv.amazingmarvin.com/api/trackedItem` which originated the bug report seems to be working fine now :)
Before closing:
Can you confirm if this was manually addressed/fixed or is it a flaky thing? I'd be concern if it's flaky and it can reproduce again randomly.

**Comment by amazingmarvin** [comment]
It seems this was caused by Marvin's sync switching to using a 3rd party cookie on https://app.amazingmarvin.com/pre. Now it's using the old authentication mechanism + a 3rd party cookie so hopefully it should work for everyone now. Re-open if you run into more sync problems on pre!
