### ISSUE TITLE
On text format for notes: JSON vs plain text

### ISSUE THREAD

**Issue by jbriales** [amazingmarvin/MarvinAPI#29]
AFAIK notes are stored as JSON prefixed with `__S:` in the `note` field,
however I noticed some tasks in my database actually just hold plain text, like this:
```json
{
  "createdAt": 1619243217639,
  "db": "Tasks",
  "title": "Create shortcut/quick action to edit current clipboard in vim standalone",
  "parentId": "403f4c65-a738-4eba-adcf-3585dde80c21",
  "day": "unassigned",
  "note": "keep TOC/window empty on left for better text positioning",
  "masterRank": 1001,
  "rank": 18465,
  "dueDate": null,
  "firstScheduled": "unassigned",
  "fieldUpdates": {},
  "updatedAt": 1619243263376,
  "_id": "ZCAndWx9tDA2ofZGwFc7",
  "_rev": "1-4c390fbf810174330e593d6bf49bffca"
}
```

Could you clarify what's going on here?
Is storing plain text a valid supported approach when using the API?

**Comment by amazingmarvin** [comment]
If you create a task using API, email, or calendar sync (for some calendars), then plain text notes are used. Marvin will continue to support plain text notes going forward! And this should be forward compatible with the markdown notes too.
