### ISSUE TITLE
[REQUEST] Get item by _id in Marvin API

### ISSUE THREAD

**Issue by jbriales** [amazingmarvin/MarvinAPI#3]
**Is your feature request related to a problem? Please describe.**
I'm trying to get a specific item by id in the API, say a task with `_id=CPfu9v6D9AgbR2Qw8x5Z`.

**Describe the solution you'd like**
e.g. `GET /api/item?id=CPfu9v6D9AgbR2Qw8x5Z`

**Describe alternatives you've considered**
I tried using the solution to get any doc [here](https://github.com/amazingmarvin/MarvinAPI/wiki/Marvin-API#read-any-doc),
but that does not seem to work. Is a doc sth different than an item?

I tried understanding how to do this via CouchDB API but did not find out how.
Besides, I'm surprised such an (apparently) basic functionality is not provided by the Marvin API directly.

**Comment by amazingmarvin** [comment]
Hey @jbriales, this is possible with the [`/api/doc` endpoint](https://github.com/amazingmarvin/MarvinAPI/issues/3).
