### ISSUE TITLE
About `Boolean` in `dependsOn` property

### ISSUE THREAD

**Issue by jbriales** [amazingmarvin/MarvinAPI#30]
The `dependsOn` property within Tasks holds a boolean value per ID:
>  * @property {Object.<String,Boolean>} dependsOn - ID => true. Task and project IDs of items that have to be completed before this item can be worked on.

What is the purpose of this Boolean?

**Comment by amazingmarvin** [comment]
Using an object like this is a JSON-friendly and efficient way to implement a set.

Add to set: `x[key] = true`
Remove from set: `delete x[key]`
In set: `!!x[key]`
Set union: `{ ...x, ... y }`

So it's similar to just storing an array of IDs, but it's faster (for large sets) and more ergonomical to search and remove.

**Comment by jbriales** [comment]
Great! Thanks so much for the explanation, makes total sense :D
