### ISSUE TITLE
About time tracking and correcting times a-posteriori

### ISSUE THREAD

**Issue by jbriales** [amazingmarvin/MarvinAPI#34]
The time-tracking API returns the `startTimes` and `stopTimes` arrays with relevant tracking timestamps for both the starting and stopping tasks, which makes me think that these values live in the central serv.amazingmarvin.com server.

Now, how does it work when we edit tracked times via the `Shift-Click` or `Alt-Click` actions in Marvin-web? Does that modify the true values in serv.amazingmarvin.com? If so, is it possible to edit tracked times in a similar manner via the API?

**Comment by amazingmarvin** [comment]
Yes, if you POST /api/retrack with body `{ "taskId": "xyz", "times": [start1, stop1, start2, stop2, ...] }` then you can update the time track info on the server. But you'll also need to update manually in the task's `times` (same array) and `duration` (sum of differences in the array) fields.
