### ISSUE TITLE
Some fields missing from TimeBlock documentation

### ISSUE THREAD

**Issue by cbrxyz** [amazingmarvin/MarvinAPI#37]
After exploring some Documents with `db=PlannerItems`, I noticed some fields were missing from the TimeBlock class documentation in the wiki.

 - The `note` field is undocumented.
 - Many documents had both `day` and `date`. Is there a difference?
 - `parentId` is undocumented.
 - `done` is undocumented.
 - Some documents also had the undocumented `timeEstimate` field.

 Thanks!

**Comment by amazingmarvin** [comment]
OK, I will include `note`. That makes sense.

But the others aren't intentionally there. This is probably just a bug from using the same editor to create time blocks as tasks (when you click in the calendar).

**Comment by cbrxyz** [comment]
Is `parentId` not important? I thought time blocks can be linked to smart lists/categories/labels?

Also, is `color` not stored in Time Block documents? You can change the color of a time block on desktop.

**Comment by amazingmarvin** [comment]
I've documented this now. These fields aren't individually stored in time blocks, but rather per-title. That way you don't have to specify the color/parent each time you make a time block called "School". Let me know if you have questions about how this works!
