### ISSUE TITLE
Getting times for id from central Marvin server

### ISSUE THREAD

**Issue by jbriales** [amazingmarvin/MarvinAPI#38]
Is there any way to query the source of truth `times` for a certain id in the central server?
I.e. retrieve the array of times for an id akin to given by `/api/track` BUT w/o starting tracking for the task.

**Comment by cbrxyz** [comment]
How about using `GET /api/doc?id={id}`? Task objects have a `times` parameter with that information and can be returned through that endpoint.

**Comment by jbriales** [comment]
I'm finding that sometimes when tracking things from the mobile app the `times` field does not seem to populate correctly (it is missing those times). In general, there has been historically some bugs in Marvin when it came to the `times` parameter (at least for me). That's why I'm interested in having access to the source of truth coming from the central server.

**Comment by amazingmarvin** [comment]
Sure, I documented this [here](https://github.com/amazingmarvin/MarvinAPI/wiki/Marvin-API#getting-time-track-info).
