### ISSUE TITLE
Note sync

### ISSUE THREAD

**Issue by Gadwood** [amazingmarvin/MarvinAPI#39]
I have a feature request if it’s possible. It’s to sync daily note, task note and project note from Marvin to see and edit them in Obsidian.

**Comment by Gadwood** [comment]
I think Marvin project note and daily note will suffise

**Comment by mltucker** [comment]
@Gadwood: this should be possible using the API to [read any document](https://github.com/amazingmarvin/MarvinAPI/wiki/Marvin-API#read-any-doc). For your ID, use 
`"di_2023-03-09"` (YYYY-MM-DD).
