### ISSUE TITLE
[BUG] /api/test does not work due to CORS (but other endpoints do)

### ISSUE THREAD

**Issue by Erudition** [amazingmarvin/MarvinAPI#4]
**Describe the bug**
Unable to successfully connect to this particular endpoint due to CORS:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed

At first I thought it was something wrong on my end, but as soon as I tried a different endpoint, my requests succeeded! It's just the /test/ endpoint that's not set to allow cross-origin requests. (In my case, from `localhost`.)

In fact, the policy for that server response seems to be, only the domain "app.amazingmarvin.com" can connect.
So only the official app can test if the API credentials are correct... xD

**Endpoint(s) in question**
`/api/test`

**Expected behavior**
The server's response contains the `Access-Control-Allow-Origin: *` header, like it does on e.g. /doc

**HTTP client:**
browser, via JS

**Additional context**
Other endpoints do not seem to have this problem, and include the appropriate `Access-Control-Allow-Origin: *`. Therefore we have the ironic situation where everything works correctly *except* the /test/ endpoint, which is designed only for checking if everything is working correctly.

**Comment by amazingmarvin** [comment]
@Erudition Can you double check that you're doing a POST request in the browser?

With `curl --verbose` I'm getting back a `access-control-allow-origin: *` as expected, whereas this header isn't sent back for `GET` requests, which would explain why you're getting a CORS error.

**Comment by Erudition** [comment]
curl --verbose works for me too actually, but in the browser log:
![image](https://user-images.githubusercontent.com/3915447/103499239-5e66b080-4e15-11eb-9baa-e60cd3ec05a0.png)

**Comment by amazingmarvin** [comment]
OK, thanks. I've figured out the issue now!
