### ISSUE TITLE
Can't find task recurrence info in API

### ISSUE THREAD

**Issue by Erudition** [amazingmarvin/MarvinAPI#42]
**Statement of purpose**

I do solemnly swear (or affirm) that this is an API bug, and not a Marvin bug. For Marvin bugs I would use the in-app "?→Contact Support" feature

**Describe the bug**
The "Marvin Data Types" page has been supremely helpful in dealing with the API responses from the couch database, which is otherwise not documented. But I keep looking everywhere on that page for how to find the rules for a recurring task - something like "every day" - it doesn't seem to be in any of the properties listed under the `Tasks` type section.

I can see when a task is an instance of a generator ("recurring task"), but are the generators a separate data type? Or are they normal looking `Task` objects and the recurrence is set elsewhere in the database somehow? Are we supposed to infer the rules by looking at the spacing between the existing instances?

I see `recurringTaskId` and `pinId` to indicate what generator an instance came from, but I also don't see where I'd be able to tell the opposite - i.e. is this task a generator itself? `isPinned` works for that type of generator, but what about recurring generators? Where are they and where are their recurrence rules? I see the recurrence rules for imported calendar items but the docs imply that's only used for external calendars.

**Comment by cbrxyz** [comment]
Did you check `db="RecurringTasks"`? I believe this is where documents representing recurring tasks lie. `db="Tasks"` documents are simply instances of recurring tasks. Those documents have attributes which represent the recurrence rules.

**Comment by Erudition** [comment]
I did not... because I did not know about it. Thank you! :)

RecurringTasks is not mentioned on https://github.com/amazingmarvin/MarvinAPI/wiki/Marvin-Data-Types or the list of `db` values, so I guess this bug report can be about that lack of documentation.

**Comment by cbrxyz** [comment]
Great! Honestly I was a little confused by the whole structure of single tasks vs. recurring tasks, too, since single events vs. recurring events are handled differently in the database...

**Comment by amazingmarvin** [comment]
Oh, sorry @cbrxyz and @Erudition: RecurringTasks weren't documented. I've added this and I'm working on a page [here](https://github.com/amazingmarvin/MarvinAPI/wiki/Recurrence) where I talk a bit about how the various types of recurrence work within Marvin.

**Comment by amazingmarvin** [comment]
Feel free to re-open if you have more questions about this.
