### ISSUE TITLE
how to get start time of time tracking while task in progress?

### ISSUE THREAD

**Issue by adamwolf** [amazingmarvin/MarvinAPI#45]
Hi!

I've read through the wiki and played around.  I may have missed something!

I'm trying to get the start time of time tracking while a task is in progress.  It doesn't look like the times list is updated in the webhook payload (which also seems likely with the times caching mentioned in the docs).

Is this something that's possible?  If not, I guess I can just use the receive time of the startTracking webhook...

Thanks!

**Comment by amazingmarvin** [comment]
I've added `"tracking"` and `"trackingSince"` to the `GET /api/me` endpoint. These tell you the ID of the task that's being tracked, and when the tracking started. Will update the documentation shortly!

**Comment by adamwolf** [comment]
Thanks so much!
