### ISSUE TITLE
About creating reminders programmatically

### ISSUE THREAD

**Issue by jbriales** [amazingmarvin/MarvinAPI#46]
Reminders and notifications can be controlled from the strategy settings.
AFAIK there is two ways over creating reminders:
- You set 'Create automatically' to On, and then all scheduled tasks with a time in it get a reminder.
- You set it to Off, and then you need to create the reminder manually.

Is there a way to create reminders (that will show also in the mobile app) programmatically
for specific tasks via the API or by setting certain fields in the DB?

**Comment by amazingmarvin** [comment]
I've documented the Reminder APIs. If you're creating tasks programmatically, then you'll need to set the reminders server-side using these APIs, regardless of your "create automatically" setting.

There's a third way but it's not enabled yet, even on pre. You can set reminders using the spacebar quick add, like "remind me to call my parents tomorrow at 8pm" or "remember: pick up kids at 15:00". Feel free to programmatically create reminders with type `"M"` (then you won't have to create a Task).
