### ISSUE TITLE
[REQUEST] Access current Marvin kudos information through API or database

### ISSUE THREAD

**Issue by cbrxyz** [amazingmarvin/MarvinAPI#5]
**Statement of purpose**
I do solemnly swear (or affirm) that this is an API feature request and not a Marvin feature request. For a Marvin feature request I would use [Product Board](https://portal.productboard.com/gvwfgxmcwqylldrxlfagmgkw).

**Is your feature request related to a problem? Please describe.**
There should be a way for users to get information about the current amount of Marvin kudos they have, the Marvin kudos level they are at, and the amount of kudos required to get to the next level.

**Describe the solution you'd like**
Either a document in the database that holds this information, or an API endpoint that can be used to retrieve this information. I think having a document store this information would be the best method, because then both using the database and the `/api/doc` endpoint of the API can retrieve the information.

**Describe alternatives you've considered**
I don't believe there are any. This information doesn't seem to be in the database anywhere, and there aren't documented endpoints on this.

**Additional context**

**Comment by amazingmarvin** [comment]
Sure! Storing this in a document isn't feasible, but you can now get this info with `GET /api/kudos` as documented [here](https://github.com/amazingmarvin/MarvinAPI/wiki/Marvin-API#get-marvin-kudos-info).

**Comment by cbrxyz** [comment]
Thanks! Is there anyway the response can also include a percentage? As in, the request would also return that the user is 79% complete with level 115.

**Comment by cbrxyz** [comment]
Also, can the `nextMultiplier` value be returned with this request? I assume that's referring to the next Kudos multiplier. It is returned in `/api/me` but not this call for some reason.
