### ISSUE TITLE
[REQUEST] allow autocompletion from task titles to be disabled/escaped

### ISSUE THREAD

**Issue by ibriscoe** [amazingmarvin/MarvinAPI#50]
**Statement of purpose**
I do solemnly swear (or affirm) that this is an API feature request and not a Marvin feature request. For a Marvin feature request I would use [Product Board](https://portal.productboard.com/gvwfgxmcwqylldrxlfagmgkw).

**Is your feature request related to a problem? Please describe.**
When using the addTask API request, autocompletion cannot be disabled, which means that titles that have the characters that trigger autocompletion, e.g. * or +, cannot be always be used in the title, or worse, trigger unwanted behaviour in Marvin, e.g. setting priority.

In my particular case, I have a list of section headings from a book I'm reading about Clojure, and certain headings contain *.  I have used this list to programmatically add tasks to a project in Marvin. At the moment, though, the titles with * aren't being added correctly.

**Describe the solution you'd like**
I'd like to be able to either add a header to the request to disable auto-completion, or I'd like a way to escape the characters in the string itself.

**Comment by mltucker** [comment]
Hey @ibriscoe, makes sense. I added an `X-Auto-Complete=false` header to the `/api/addTask` endpoint so that you can completely disable autocompletion.
