### ISSUE TITLE
Add habits to API/Webhooks

### ISSUE THREAD

**Issue by jessicatmt** [amazingmarvin/MarvinAPI#7]
Request: Add Habits to API/webhooks so that they can be used with other apps like Beeminder.

**Comment by cbrxyz** [comment]
Additionally, when habits are supported in the API, is there anyway the calculated client-side information can be included in the API response? Aka, information not directly in the database, like "Current Grade" or "Trend".

**Comment by amazingmarvin** [comment]
@jessicatmt @cbrxyz OK, I have implemented habit webhooks and you can test this out on pre (https://app.amazingmarvin.com/pre). Stats are included with the recordHabit webhook. I am currently writing documentation. Please re-open or create a new issue if you run into any issues with these webhooks!

I plan to release new versions this week (web/desktop and mobile) and these webhooks will be available there.

**Comment by brendanshoe** [comment]
@amazingmarvin Only the webhook portion of this was addressed, correct? Right now the only way to log a habit is via the CouchDB API from what I can tell.
