### ISSUE TITLE
Documentation for /api/me

### ISSUE THREAD

**Issue by cbrxyz** [amazingmarvin/MarvinAPI#9]
This API call seems to have a lot of helpful information, but I can't find documentation for what many of the fields do. For some fields like `userId` or `signupAppVersion`, it's clear. However, for other fields (such as `slaves` or `taxType`), the use case or possible values aren't clear.

Could documentation be added for the fields returned by this call?

**Comment by amazingmarvin** [comment]
OK @cbrxyz, now that I've documented this [here](https://github.com/amazingmarvin/MarvinAPI/wiki/Marvin-API#me), I'm only including fields that I thought would be relevant for the user. The fields you mentioned are no longer included (thought slave accounts are for multi-seat billing and taxType is just a field from Stripe).
